### ISSUE TITLE
Support the browser

### ISSUE THREAD

**Issue by esphen** [mqttjs/mqtt-packet#11]
Hi,

We are developing a browser plugin for previewing websocket traffic, and are looking into your package for parsing MQTT-messages. Your package caught our eye; the implementation looks great, good job.

I couldn't help but notice, however, that you depend on `bl` and some other node.js stuff. Do you think it could be possible to support the browser as well? If so, it would be a great help for us.

Alternatively - do you know of any other parsing library for MQTT? I looked at MQTT.js, but that is a whole client/server-thing, we just need the parsing logic.

**Comment by mcollina** [comment]
It works perfectly with browserify or webpack, as MQTT.js works in the
browser.
As it seems you are talking about using it as is, without browsefy or
webpack. Right?
Il giorno ven 1 apr 2016 alle 23:16 Espen H <notifications@github.com> ha
scritto:

**Comment by esphen** [comment]
That's good to hear, I only saw references to node in the readme. 

Correct, Ideally I would like to just be able to put the source file or a dist file right in the project, as there is no build system as of now. I tried to simply require the source, but that didn't really work too well.

**Comment by mcollina** [comment]
You can create a standalone bundle with browserify. Have a look. This module is built for speed and throughput, and it heavily relies on Node Streams and Buffer.
I have no time to rewrite this for the browser only... you might want to fork it.

**Comment by esphen** [comment]
I did what you said - created a standalone bundle via browserify; it works great. Thanks for your help!
