### ISSUE TITLE
Generate 'puback' package can't set 'qos' properties

### ISSUE THREAD

**Issue by dim0147** [mqttjs/mqtt-packet#116]
Hi, I want to create 'puback' package which has 'qos' property is **1** but it always 0:
![image](https://user-images.githubusercontent.com/44487221/121761543-fbffa200-cb62-11eb-9fea-71ff4d1e507f.png)
![image](https://user-images.githubusercontent.com/44487221/121761553-0752cd80-cb63-11eb-81df-a7297ed45954.png)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by dim0147** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I have make a pull request, can you check?

**Comment by scarry1992** [comment]
But puback package hasn't qos field by specification..for what you need this option?

**Comment by dim0147** [comment]
Currently, I'm working with Facebook sites and they use packages that required this property to be set and I need to access this field.

**Comment by scarry1992** [comment]
Look, puback always has a qos=1. Use this spec description knowledge for puback processing in your own code.
