### ISSUE TITLE
SUBSCRIBE packet with no payload

### ISSUE THREAD

**Issue by ccarcaci** [mqttjs/mqtt-packet#119]
I've implemented this test:
```
test('SUBSCRIBE packet has no payload', (done) => {
  const subscribe: ISubscribePacket = {
    cmd: 'subscribe',
    messageId: 0,
    subscriptions: [
      {
        topic: 'topic',
        qos: 0,
      },
    ],
  }
  const subscribePacket: Buffer = mqttPacket.generate(subscribe)
  const truncSubscribe = Buffer.alloc(2)
  subscribePacket.copy(truncSubscribe, 0, 0, 2)
  truncSubscribe[1] = 0x00 // No payload, Remaining Length = 0

  const parser = mqttPacket.parser(opts)
  parser.on('error', (error) => {
    expect(error.message).toBe('SUBSCRIBE packet MUST have payload')
    done()
  })
  parser.on('packet', () => {
    throw new Error('SUBSCRIBE packet with no payload is invalid')
  })
  parser.parse(truncSubscribe)
})
```

I've tampered a SUBSCRIBE packet by removing the payload and forcing the Remaining Length field to zero.

But the specification here: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901030
stated that the SUBSCRIBE packet MUST have a payload.

My tampered packet should be invalid or malformed. Nonetheless the parser is correcting parsing the packet emitting the 'packet' event making this test fail.

Is this ok?

**Comment by mcollina** [comment]
Not really, would you like to send a PR?

**Comment by ccarcaci** [comment]
@mcollina sure :)
https://github.com/mqttjs/mqtt-packet/pull/120

**Comment by ccarcaci** [comment]
Fix merged!
