### ISSUE TITLE
Unexpected identifier error in browserifying mqtt

### ISSUE THREAD

**Issue by sandro-k** [mqttjs/mqtt-packet#12]
As reported in mqttjs/MQTT.js#417, there is an `Unexpected identifier error` in mqtt-packet. Currently there are two 160 unicodes (Non-breaking space) vs 32 (Normal space) at https://github.com/mqttjs/mqtt-packet/blob/master/parser.js#L355 and https://github.com/mqttjs/mqtt-packet/blob/master/parser.js#L370

**Comment by mcollina** [comment]
All of this is released both on the 3.x and 4.x lines. Please verify everything works ok :)
