### ISSUE TITLE
Call `stream.destroy(err)` instead of `stream.emit('error', err)`

### ISSUE THREAD

**Issue by vishnureddy17** [mqttjs/mqtt-packet#126]
Referencing another issue commented by @mcollina:

> Oh! I forgot we were doing that in this module. This problem was fixed long ago in Node.js. We should be calling `stream.destroy(err)` instead.
> 
> Would you like to send a PR?
> 
> _Originally posted by @mcollina in https://github.com/mqttjs/mqtt-packet/issues/124#issuecomment-1028728226_

Would be happy to open a PR for this, but had a couple of questions here:
1. Wouldn't this be a breaking change? 
2. Is this truly the desired behavior? Suppose someone tries to push a CONNECT packet with an invalid protocol version. This is an error, but do we want to destroy the entire stream? Or just fail that one packet?

**Comment by mcollina** [comment]
It will be a breaking change and also a bugfix. The stream "contract" is that the stream became unusable after error or close event.
