### ISSUE TITLE
Adopt standard

### ISSUE THREAD

**Issue by mcollina** [mqttjs/mqtt-packet#17]
What do you folks thinks?

http://npm.im/standard

**Comment by sandro-k** [comment]
> No semicolons – It's fine. Really!

:+1:

**Comment by mcollina** [comment]
Any takers? :D

**Comment by sandro-k** [comment]
I can have a look at it in two/three weeks.. if anyone is available earlier just go ahead.

**Comment by wuhkuh** [comment]
I was already working on this. Also working on updating mosca. You can expect some PRs in a few weeks.

**Comment by wuhkuh** [comment]
I found some unused functions that standard is warning me about. Should we deprecate (read: remove) those functions or do we add an exception, in case there is a repository using this as a dependency?

I'm talking specifically about the 'writeStringNoPos' and 'writeBuffer' functions in writeToStream.js
The rest of the refactoring will be uploaded to my fork until it's clear what to do with these two functions.

**Comment by mcollina** [comment]
@wuhkuh please remove everything that is unused, these are probably leftovers from a previous refactoring.

**Comment by sandro-k** [comment]
@wuhkuh thanks for the PR..
