### ISSUE TITLE
Chunked packets

### ISSUE THREAD

**Issue by GermanBluefox** [mqttjs/mqtt-packet#24]
**Problem:**
   I tried to use this package with [HIVE-MQ-WebSockets client](http://www.hivemq.com/demos/websocket-client/) and it does not work. The problem is, that this client (HIVE-MQ) does not expects chunked packets. I understand, that this is a problem of HIVE-MQ, but just now it is my problem :)

**Solution:**
  Build first the whole packet as a buffer and send all bytes together.

https://github.com/GermanBluefox/mqtt-packet/blob/master/writeToStream.js

**Result:**
  After I modified writeToStream.js file and I could communicate with HIVE-MQ and everything was fine. I could not test client part of mqtt-packet and tested only *connack*, *publish*, *confirmation*, *suback*, *emptyPacket*. 
*connect*, *subscribe* and *unsubscribe* are untested.
 I understand, that the performance will decrease slightly, but it is much better, that not working communication.

Please check the changes and say your opinion.

P.S. Just cant find the newest branch and do not understand where to place my pull request.
I see there is a brunch "packet" and the solution there is similar.

**Comment by mcollina** [comment]
The problem is in https://github.com/maxogden/websocket-stream, which behaves in object mode rather than merging together all the chunks. Would you like to try a PR? we need to implement `_writev` there, and merge all the chunks in a single one.

**Comment by GermanBluefox** [comment]
E.g. this code will not work too: 
https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.cpp#L263

And it does not work :) 

>Would you like to try a PR?

Can't follow you. 
In [this](https://github.com/mqttjs/mqtt-packet)  repository or in this [one](https://github.com/maxogden/websocket-stream) ?

**Comment by mcollina** [comment]
as far as I know, this is a problem for WebSockets, which are not currently supported by PubSubClient. Or am I wrong?

This one: https://github.com/maxogden/websocket-stream, as you are using websocket.
Or I misunderstood.

**Comment by GermanBluefox** [comment]
No it is not only via WebSockets. There is a popular (very popular) client for ESP8266 based on code what I showed above and ALL these clients does not work . And all the users asking me: Why? :)

I must found the solution very quickly.

**Comment by GermanBluefox** [comment]
As you can see the code is from knolleary itself and he is almost the inventor of MQTT.

**Comment by mcollina** [comment]
Let me clarify: you are free not to use this.

**Comment by GermanBluefox** [comment]
Hey. Hey. It is great job, what you have done. 

It just requires a small fix. :)

**Comment by mcollina** [comment]
Ok :).

You can check the MQTT spec, and see if there is anything about fitting any part of an MQTT packet on a single TCP packet. There isn't.
There is a problem on WebSocket with MQTT.js, I just don't have time to fix it. But the fix is not what you propose.

I think you have some other problem.

**Comment by wuhkuh** [comment]
@GermanBluefox 
The problem is we can't just make changes when requested. This problem may be on either ends, in the Hive-MQ-WebSockets client or, as you suggest, in this packet generator.

This is where the [MQTT standard](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html) comes in.

**Comment by GermanBluefox** [comment]
I understand you both and I am rather often in the same situation too. Just now I don't care about Hive-MQ, but about ESP8266 (tcp). 

And the strangest thing is that knolleary (who wrote the cpp mqtt client and node-red) is exactly this man, who pushed MQTT at IBM. as you can see 
![image](https://cloud.githubusercontent.com/assets/4582016/22611221/af1884cc-ea69-11e6-9d12-c38380e814bd.png)
75% of Chairs is IBM. 
I am so confused. 

I am network specialist for over 17 years and I absolutely know, that TCP is a stream and not a packet protocol. And I understand you, that you have done everything according the specification, but.... it does not work with a clients. :) And clients do not care about it. You a guilty (in this case me) that you broke the communication.

I cannot use just mqtt-packet, because I use directly only mqtt-connection. So I must to fork two packets. 
May be I should talk with Nick (knolleary)

**Comment by GermanBluefox** [comment]
May be with a flag? 
chunking: true/false :)

**Comment by wuhkuh** [comment]
Well, to keep things simple:
> And clients do not care about it.

There is your issue. A specification is in place to enforce the same protocol at both parties. Again, if we've made a mistake regarding the specification, please let us know. 
If the client doesn't follow the MQTT specification, then it simply is not a MQTT client - and there's nothing on our end we can do.

**Comment by knolleary** [comment]
An mqtt packet may be split over multiple TCP packets. That's just a fact. Clients and servers need to handle it.

Even if a client constructed the packet as a single buffer and passed it to the network stack to write, it may still get split into multiple TCP packets further down the stack. You cannot assume a client is able to guarantee a 1-to-1 relationship. You cannot assume every mqtt publish payload will fit in a TCP packet.

(Just for the record, I had nothing to do with the creation of MQTT, but I do have a role in its ongoing existence)

**Comment by GermanBluefox** [comment]
Looks like the cpp code is OK and can handle gaps in bytes of one packet with up to 15 seconds.
So I should inform all the clients about problem.
Thanks to all for conversation.
