### ISSUE TITLE
Add ability to configure numCache

### ISSUE THREAD

**Issue by kirilknysh** [mqttjs/mqtt-packet#28]
In current implementation a `numCache` is create by default (file numbers.js) and it contains 65536 buffers with predefined values. That leads to quite high memory consumption: ~14Mb of memory (node process) can be saved.

For sure it's always a trade off between memory and performance that's why I'd like to propose to configure `numCache`: to give an ability to either create cache during start or create buffers on demand and, potentially, cache created.

I did a quick comparison (on `benchmarks/writeToStream.js`):

- current implementation gives
```
Total time 2703
Total packets 1000000
Packet/s 369959.3044765076
```

- a quickly patched version:
```
var buffer;

const handler = {
    get: function (target, name) {
        const i = ~~name;

        buffer = new Buffer(2);
        buffer.writeUInt8(i >> 8, 0, true);
        buffer.writeUInt8(i & 0x00FF, 0 + 1, true);
        return buffer;
    }
};

module.exports = new Proxy({}, handler);
```
gives:
```
Total time 3156
Total packets 1000000
Packet/s 316856.7807351077
```

Of course this is not a "production"-ready patched code and it can be improved. That's rather an example to show that performance degradation is not so big.

I do understand that most developers prefer speed over memory consumption that's why I propose to leave it as an option.

Please let me know if it works for you. I can prepare a PR with a good solution.

Thanks!

**Comment by mcollina** [comment]
I would not merge any PRs that have any form of performance degradation.

How did you measured the 14MB? 

2 * 65536  = 131072 _bytes_ = 128 KB.

Something else should be going on. Maybe we need to allocate a big buffer, and then slice through it.

**Comment by kirilknysh** [comment]
I just took the existing `number.js`, added `setInterval(() => {}, 9999);` (just not to finish the process immediately) and run `node number.js`. Then I measured memory with just regular `top` command (MacOS Sierra, 10.12.4, node v6.5.0).

Node process with the original `number.js` - 22Mb
Node process with patched code - 9Mb

Keep in mind that this is not JS heap but node process itself.

**Comment by mcollina** [comment]
@kirilknysh so, how do you think we can make this configurable? Also, we might check if using an array improve things.

**Comment by kirilknysh** [comment]
I've tested with an array. Regarding memory - no big difference in both: memory usage and performance.

How to make it configurable - not really sure. Unfortunately, I'm not closely familiar with the overall architecture of the mqttjs. From the first sight - the best candidate is `connect` packet in `writeToStream.js` (assuming that `connect` command is always the first in a flow). Then it could be done similar to settings like `protocolId`, `protocolVersion` etc.

**Comment by mcollina** [comment]
I don't think it's feasible in that way, and I would not like to change the API.

How about we do:

mqttPacket.cacheNumbers = false

which then replaces the current system? We can do that with a getter I think.

Would you like to attempt a PR?

**Comment by kirilknysh** [comment]
Sure, I'd love to attempt. One thing: how do you expect to get access to `mqttPacket.cacheNumbers` from `writeToStream.js`?

**Comment by mcollina** [comment]
I think we might call a method in `writeToStream` and replace it? Be careful to lazy-load `numbers.js` only when needed.

**Comment by kirilknysh** [comment]
How about API like:
```
var mqttPacket = require('mqtt-packet');
mqttPacket.writeToStream.cacheNumbers = false;
...
mqttPacket.writeToStream(packet, client.stream)
...
```
`numCache` would be initialized in the first call of `writeToStream` based on `cacheNumbers` prop (either generate cache or not). Potential draw back - a bit slower first call.

**Comment by mcollina** [comment]
that'd be good for me.
