### ISSUE TITLE
parse error due to unexpected characters

### ISSUE THREAD

**Issue by pmorjan** [mqttjs/mqtt-packet#3]
the Chrome parser failes on generate.js due to some unexpected characters:
0xc2 0xa0 in front of "" and clean 
    
    $ md5sum generate.js
    c649514871233fb093c4461f8395e054  generate.js
    
    $ grep -P -n "[\x80-\xFF]" generate.js
    44:    , clientId = opts.clientId || ""
    76:     (clientId || clean)) {

    $ grep  -P "[\x80-\xFF]" generate.js | xxd
    0000000: 2020 2020 2c20 636c 6965 6e74 4964 203d      , clientId =
    0000010: 206f 7074 732e 636c 6965 6e74 4964 207c   opts.clientId |
    0000020: 7cc2 a022 220a 2020 2020 2028 636c 6965  |.."".     (clie
    0000030: 6e74 4964 207c 7cc2 a063 6c65 616e 2929  ntId ||..clean))
    0000040: 207b 0a                                   {.

Thanks! 
peter

**Comment by mcollina** [comment]
It is not really clear what's the problem and how to fix it. Also, what is `generate.js`? Would you mind sending a PR to address this issue?

**Comment by pmorjan** [comment]
The source file 'generate.js' contains unprintable characters in line 44 and 76.  These make the Chrome browser fail when trying to parse it. (mqtt.js via browserify). The error message that Chrome prints out is :
 'Uncaught SyntaxError: Unexpected string' . 

The  'Unexpected strings'  are invisible in regular editors. They are shown as regular spaces but are actually two bytes (0xc2 0xa0 instead of 0x20). You have to use an hex editor/parser to make them visible. (like I did with xxd).

Fix: Open the file in any text edtor and replace the character in 44:32  and 76:18 by a single space.
Thanks!
peter

**Comment by pmorjan** [comment]
Fixed in ce77c0e292bd.
Thanks for processing so quickly.
peter

**Comment by mcollina** [comment]
No worries! ;)
Il giorno mar 1 set 2015 alle 17:23 Peter Morjan <notifications@github.com>
ha scritto:
