### ISSUE TITLE
nextTick  Error 

### ISSUE THREAD

**Issue by saikatharryc** [mqttjs/mqtt-packet#34]
have encountered a problem related `nextTick`.

`nextTick is not a function`

as per my view its coming from [here](https://github.com/mqttjs/mqtt-packet/blob/master/writeToStream.js#L19)

and making that line `nextTick.nextTick()` is working fine.

**Comment by mcollina** [comment]
Can you upload a reproducible example?

**Comment by saikatharryc** [comment]
i'm unable to reproduce this same scenario,
because this is an dependency of another dependency that i used.

but, in that `writeToStream.js` file you have used [process-nextick-args](https://www.npmjs.com/package/process-nextick-args)

like below:
```
var nextTick = require('process-nextick-args')
nextTick(uncork, stream)
```

while as per their documentation: 
it would be something like below:

```
var nextTick = require('process-nextick-args')
nextTick.nextTick(uncork, stream)
```

![image](https://user-images.githubusercontent.com/15653282/36477168-3916fec6-1726-11e8-80d0-b897e716ec4f.png)

**Comment by mcollina** [comment]
This library has been updated to the new version as well.

**Comment by carloscolombo** [comment]
I am running into the same issue.

the `writeToStream.js on line 8`

```
var nextTick = require('process-nextick-args').nextTick
```

but the documentation from the `process-nexttick-args` says it should be something like (remove the `.nextTick`)

```
var nextTick = require('process-nextick-args')
```

I think this is what @saikatharryc meant to type in his example. 

Manually removing the `.nextTick` resolved the issue for me.

**Comment by mcollina** [comment]
You should update your webpack. It has a bug that is causing this.
