### ISSUE TITLE
Why is the version of mqtt-packet different between client and server?

### ISSUE THREAD

**Issue by dxil** [mqttjs/mqtt-packet#40]
Hi,  : )
mqtt-packet  looks really neat! !   I'm wondering why is the version different between the client and server ?  

server:  mosca dependency is mqtt-connection and mqtt-connection dependency is mqtt-packet v3.5.0
client:    mqtt -> mqtt-packet v5.6.0

and some functions in package is different

In v5.6 like this
```javascript
var stream = new Accumulator() // in generate.js
stream.write(buffer) // in writeToStream.js
```
but in v3.5 maybe 
```javascript
buffer.writeUInt8() // in generate.js that has become writeToStream.js (v5.6.0)
```
Look forward to your reply.
Thank you! 🍰

**Comment by mcollina** [comment]
Because I've not updated Mosca in a very long time. I'd recommend you to look into https://github.com/mcollina/aedes.

**Comment by dxil** [comment]
Oh!  This is awesome！Thank you for your reply！
( What do you think about 3.1.1 and 5.0? Will you continue to implement version 5.0?)

**Comment by mcollina** [comment]
It's not in my plans. If anyone wants to start working on it, please help :D.
