### ISSUE TITLE
In specification is not named Message Identifier but Packet Identifier

### ISSUE THREAD

**Issue by SyMind** [mqttjs/mqtt-packet#47]
I think the variable name and error message should consistent with the specification as follow.
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718025

**Comment by mcollina** [comment]
Historically this has always been message identifier. I'm not sure that the breakage would be worth the consistency. However, if you would like to send a PR that documented this in the README, it would be great.

Also, we could add a getter for `packetId` to https://github.com/mqttjs/mqtt-packet/blob/master/packet.js. Would you like to send a PR in that direction if you prefer? We have to keep the old property.
