### ISSUE TITLE
Rebase writing system from stream-writed in stream to buffer-writed

### ISSUE THREAD

**Issue by scarry1992** [mqttjs/mqtt-packet#48]
I want to redo the writing system as mentioned in the title. That'll give us less overhead by ws/wss connections, generate less payload when processing fewer socket frames. @mcollina, what do you think about it?

**Comment by mcollina** [comment]
The reason why we switched to this was because on tcp and ssl sockets is significantly better to avoid copying the buffers. That slows things down significantly. Ideally the .cork() and writev implementation in Node and ws should take care of chunking and avoiding the problem. There might be something to fix in websocket-stream.

**Comment by scarry1992** [comment]
@mcollina, so if I want to send packet per frame, I must to implement cork() in websocket-stream. Right?

**Comment by mcollina** [comment]
I think it should be https://github.com/maxogden/websocket-stream/blob/master/stream.js#L154-L166.

Why is this not working?

**Comment by scarry1992** [comment]
@mcollina, as I see, writev turned on by options objectMode is false, but objectMode value by default is false. So, by default I getting packet per frame, but that`s not realy. I`m getting all properties of packet per frame separatly. I see it on my broker.

**Comment by mcollina** [comment]
we should create it in not in object mode in MQTT.js.

**Comment by scarry1992** [comment]
What do you mean? We must to implement it in ws connector in mqtt.js? But how?

**Comment by mcollina** [comment]
In MQTT.js  we need to make sure that the websocket stream is not in object mode

**Comment by scarry1992** [comment]
So, if I added property objectMode: false to wsOptions in my connection, I`m getting set up writev handler in websocket-stream. Then in mqtt-packet in generate function stream's try cork(). But writable stream which's piped with writable stream in mqtt.js can't make writev. As I see, I must to imlement writev in _setupStream and to process objectMode for creating writable stream inside that handler. Right?

**Comment by mcollina** [comment]
What do you mean with "mqtt.js can't make writev".

**Comment by mcollina** [comment]
Which Writable? This https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L245 is used when reading the packets, not when writing them.

**Comment by scarry1992** [comment]
Oh, I see. But I realy can't understand what can I do for to implement sending packet per message. Can you to explain to me, please?

**Comment by mcollina** [comment]
I do not know _where_ they get chunked up, and where cork() is failing us. https://github.com/maxogden/websocket-stream/blob/master/stream.js#L76 might likely be the issue.

**Comment by scarry1992** [comment]
https://github.com/maxogden/websocket-stream/blob/master/stream.js#L76 probably you are right. Because I'm debugging my app and I see in mqtt-packet stream is Duplexify, but debug way creating Transform stream. And in Duplexify stream objectMode setted in true.

**Comment by mcollina** [comment]
I think the fix should come to WebSocket stream.

**Comment by scarry1992** [comment]
@mcollina, do you know the maintainer of websocket-stream package? He is streel alive?) He don`t have activity on github from october 2018..

**Comment by scarry1992** [comment]
That'a great! Can you spell me: When I remove that initial stream by duplexify and leave stream = proxy only, everything works well. Can you tell me why you are doing stream by duplexify and what benefits it gives.

**Comment by mcollina** [comment]
It is used to handle the delayed open scenario. We can remove it, but we might have to change some other things, as we can’t write until the ws is open.

**Comment by scarry1992** [comment]
Duplexify method obj() set objectMode setting in true automaticaly. And if I extending obj() logic with options parameter, it setup objectMode truely, but don't working anyway. Maybe some issue in duplexify too?

**Comment by mcollina** [comment]
You might have to add our _writev implementation to the duplexify stream as well.

**Comment by scarry1992** [comment]
That's right, but if I added _writev implementation to duplexify, I'm getting packets separated on 2 chunks. (first byte in first frame, but all another bytes in second frame) W/o duplexify it's working as well (all bytes in first frame).

**Comment by mcollina** [comment]
Then we should remove duplexify and handle the connection state separately.

**Comment by scarry1992** [comment]
@mcollina, I tried remove duplexify from dependensies, but a lot of duplexify logic needed in server side. I fix it, but need you review. https://github.com/maxogden/websocket-stream/pull/147

**Comment by scarry1992** [comment]
@mcollina, and I retested all mqtt.js with that fix - everything ok
