### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by muz3** [mqttjs/mqtt-packet#63]
hi team, I received the following warning on my app build, after tracing it down, I found out mqtt-packet still uses Buffer() here "https://github.com/mqttjs/mqtt-packet/blob/master/constants.js#L131". Can we please get it fixed? thanks,

"(node:8008) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead."

**Comment by mcollina** [comment]
would you mind sending a PR?

Il giorno sab 27 lug 2019 alle 00:06 rayw <notifications@github.com> ha
scritto:

**Comment by muz3** [comment]
done. PR is submitted here: https://github.com/mqttjs/mqtt-packet/pull/64

changed from 'new Buffer(1)' to Buffer.alloc(1). no more deprecated warning, and passed npm test.
