### ISSUE TITLE
_parseVarByteNum  parser error

### ISSUE THREAD

**Issue by blue-bird1** [mqttjs/mqtt-packet#72]
Will cause `RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds in special packets

`https://gist.github.com/blue-bird1/5f79ca8665c4fc9dffb7cd3ed3233490`

**Comment by bkp7** [comment]
PR #100 has been committed and in the absence of a specified test for this, can we assume this issue is now fixed and close it?
