### ISSUE TITLE
Reason Codes seem not to be enabled

### ISSUE THREAD

**Issue by Andreyooo** [mqttjs/mqtt-packet#80]
E.g. when connecting to test.mosquitto.org, no reason code is delivered in connack packet

**Comment by bkp7** [comment]
In v5.0 the Variable Header can be reduced in length if the Reason Code is 0 and/or there are no Properties. Thus each of the following are valid:
```js
[
  0x40, 0x02, // Fixed Header (PUBACK, Remaining Length - 2 Bytes)
  0x00, 0x2a, // Packet Identifier MSB, LSB: 42
]
```
```js
[
  0x40, 0x03, // Fixed Header (PUBACK, Remaining Length - 3 Bytes)
  0x00, 0x2a, // Packet Identifier MSB, LSB: 42
  0x00 // PUBACK Reason Code: Success
]
```
```js
[
  0x40, 0x04, // Fixed Header (PUBACK, Remaining Length - 4 Bytes)
  0x00, 0x2a, // Packet Identifier MSB, LSB: 42
  0x00, // PUBACK Reason Code: Success
  0x00 // Property Length
]
```
If the format used is the 2nd or 3rd the reason code will be present. But, if it's in the 1st format as used by Mosquitto and HiveMQ, the reason code will be omitted by mqtt-packet unless there are properties present.
