### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by qm3ster** [mqttjs/mqtt-packet#93]
Would a PR to convert this to Typescript be accepted?
I am trying to refactor MQTT.js, and I am running into trouble because of the massive client options object, which goes from containing pieces of `require('url').parse` output to being used as the prototype of connect packet.
Having small atomic interfaces for the parameters to connect, publish, etc would be useful.

**Comment by mcollina** [comment]
I would be ok in having types added, but keeping the project in js.
You can add tests with http://npm.im/tsd

**Comment by qm3ster** [comment]
Any reason in particular?

**Comment by mcollina** [comment]
I'm the main maintainer of this module and my TS skill is not great. Moving the project to TS will make impossible for me to keep maintaining this project.

**Comment by qm3ster** [comment]
Understood
