### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by Anubarak** [mqttjs/mqtt-packet#94]
Unfortunately our client decided to trust a third company that sold them tablets with a chromium 46 on them. So we need to support that old engine.

When I try to run your lib on the browser the following error appears
> Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode./node_modules/mqtt-packet/parser.js @ app.js:8170
__webpack_require__ @ app.js:770
fn @ app.js:130
(anonymous function) @ mqtt.js?3409:1
./node_modules/mqtt-packet/mqtt.js @ app.js:8115
__webpack_require__ @ app.js:770
fn @ app.js:130
.......

That file points to your Parser
```JS
/*!********************************************!*\
  !*** ./node_modules/mqtt-packet/parser.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("const bl = __webpack_require__(/*! bl */ \"./node_modules/bl/bl.js\")\nconst EventEmitter = __webpack_require__.........

/***/ }),



const bl = require('bl')
const EventEmitter = require('events')
const Packet = require('./packet')
const constants = require('./constants')
const debug = require('debug')('mqtt-packet:parser')

class Parser extends EventEmitter {
```

But that's of course not legit on old browsers.
Would it be possible to run your lib through babel and convert it propperly?

**Comment by mcollina** [comment]
You can run it through babel yourself in your webpack config.

**Comment by Anubarak** [comment]
Thanks for your fast reply.
Could you eventually tell me how? I'm not that familiar with it

**Comment by mcollina** [comment]
It really depends on your webpack config and I have not time at the moment to debug it :(.
